essaie_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('List_product/',include('List_product.urls')),
    path('inseed/',include('inseed.urls')),
    path('forum/', include('forum.urls')),
    path('inseed_apropos/',include('inseed_apropos.urls')),
    path('careers/',include('career.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('intranet/',include('intranet.urls')),
    path('user_manage/',include('user_manage.urls')),
    path('analytique/',include('analytique.urls')),
    path('ajax_emp/',include('ajax_emp.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path

app_name = "forum"

from . import views 

urlpatterns = [
    path('', views.forum_list, name='forum_list'),
    path('discusions_list/<int:forum_id>/', views.discusions_list, name='discusions_list'),
    path('post_list/<int:discusion_id>/', views.post_list, name='post_list'),
    path('add_post/<int:discusion_id>/', views.add_post, name='add_post'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Forum (models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Discusion (models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Post (models.Model):
    content = models.TextField()
    discussion = models.ForeignKey(Discusion, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Post by {self.created_by} on {self.discussion.title}'

forum/forms.py
from django import forms
from .models import Post
class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['content']
        widgets = {'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Content',},)}

forum/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404,redirect
from .models import Forum, Discusion, Post, User
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

def forum_list(request):
    forums = Forum.objects.all()
    return render(request, 'forum/forum_list.html', {'forums': forums})

def discusions_list(request, forum_id):
    forum = get_object_or_404(Forum, id=forum_id)
    discusions = Discusion.objects.filter(forum=forum)
    return render(request, 'forum/discusions_list.html', {'forum': forum, 'discusions': discusions})

def post_list(request, discusion_id):
    discusion = get_object_or_404(Discusion, id=discusion_id)
    posts = Post.objects.filter(discussion=discusion).order_by('-created_at')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    return render(request, 'forum/post_list.html', {'discusion': discusion, 'posts': posts})

def add_post(request, discusion_id):
    discusion = get_object_or_404(Discusion, id=discusion_id)
    if request.method == 'POST':
        content = request.POST.get('content')
        if content:  # Vérifie si le contenu n'est pas vide
            post = Post(
                content=content,
                discussion=discusion,
                created_by=request.user if request.user.is_authenticated else None
            )
            post.save()
            return redirect('forum:post_list', discusion_id=discusion.id)
    return render(request, 'forum/add_post.html', {'discusion': discusion})

# def add_post(request,discusion_id):
#     discusion = get_object_or_404(Discusion, id=discusion_id)
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.discussion = discusion
#             post.created_by = request.user
#             post.save()
#             return redirect('forum:post_list', discusion_id=discusion.id)
#     else:
#         form = PostForm()
#     return render(request, 'forum/add_post.html', {'discusion': discusion, 'form': form})

forum/templates/forum/add_post.html
<section class="container">
    <hr>
    <form class="form-group" action="{% url 'forum:add_post' discusion.id %}" method="post">
        {% csrf_token %}
        <div>
            <!-- <textarea id="content"></textarea> -->
            <label class="form-label" for="validationTextarea">Commenter</label>
            <textarea class="form-control is-invalid" id="validationTextarea" placeholder="Required example textarea"
                required name="content"></textarea>
            <br>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</section>

forum/templates/forum/discusions_list.html
{% extends 'index.html' %}

{% block content %}

<section class="container my-5">
    <h1>Les Sujet </h1>
    <div class="card" style="width: 90%;">
        <ul class="list-group list-group-flush">
            {% for discusion in discusions %}
            <li class="list-group-item">
                <a class="text-decoration-none" href="{% url 'forum:post_list' discusion.id %}">
                    <h4> {{ discusion.title }}</h4>
                    <span class="d-block justify-content-espace-between ">Pulier par : {{ forum.created_by.username }}
                    </span>
                    <span class="d-block justify-content-espace-between ">Le {{ forum.created_at|date:"d/m/Y" }}
                    </span>
                </a>
            </li>
            {% empty %}
            <div>Aucun forum</div>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

forum/templates/forum/forum_list.html
{% extends 'index.html' %}

{% block content %}
<section class="container my-5">
    <div style="width: 90%; margin: auto;">
        <h1 class="text-center text-decoration-underline">Les Categories de forums : </h1>
        <ul class="list-group list-group-flush">
            {% for forum in forums %}
            <li class="list-group-item mt-2 shadow-sm">
                <a class="text-decoration-none" href="{% url 'forum:discusions_list' forum.id %}">
                    <h4>{{forum.name}}</h4>
                </a>
                {{ forum.description}}
                <span class="d-block justify-content-espace-between ">Pulier par : {{ forum.created_by.username }}
                </span>
                <span class="d-block justify-content-espace-between ">Le {{ forum.created_at|date:"d/m/Y" }}
                </span>
            </li>
            {% empty %}
            <div>Aucun forum</div>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

forum/templates/forum/post_list.html
{% extends 'index.html' %}

{% block content %}
<section class="container my-5">
    <!-- Titre et Contenu de la Discussion -->
    <h1>{{ discusion.title }}</h1>
    <p>{{ discusion.content }}</p>
    {% include 'forum/add_post.html'%}
    <hr />
    <!-- Liste des Commentaires Existants -->
    <div class="comments-section">
        <ul class="list-group list-group-flush">
            {% for post in posts %}
            <li class="list-group-item bg-light mt-2 shadow-sm">
                <h4><strong>{{ post.created_by.username }}</strong></h4>
                <p>{{ post.content }}</p>
                </span>
                <span class="d-block justify-content-espace-between ">Le {{ post.created_at|date:"d/m/Y" }}
                </span>
            </li>
            {% empty %}
            <div>Aucun forum</div>
            {% endfor %}
        </ul>

    </div>

    <!-- Formulaire pour Ajouter un Commentaire -->

</section>
{% endblock %}