career/urls.py
from django.urls import path
from django.conf import settings
from . import views


app_name = "career"

urlpatterns = [
    path('', views.home, name="career"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('postuler/', views.postuler, name="postuler"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('register', views.register, name="register"),
]

essaie_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('List_product/',include('List_product.urls')),
    path('inseed/',include('inseed.urls')),
    path('forum/', include('forum.urls')),
    path('inseed_apropos/',include('inseed_apropos.urls')),
    path('careers/',include('career.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('intranet/',include('intranet.urls')),
    path('user_manage/',include('user_manage.urls')),
    path('analytique/',include('analytique.urls')),
    path('ajax_emp/',include('ajax_emp.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path

app_name = "forum"

from . import views 

urlpatterns = [
    path('', views.forum_list, name='forum_list'),
    path('discusions_list/<int:forum_id>/', views.discusions_list, name='discusions_list'),
    path('post_list/<int:discusion_id>/', views.post_list, name='post_list'),
    path('add_post/<int:discusion_id>/', views.add_post, name='add_post'),
]

products/urls.py
from django.urls import path
app_name = "products"
from . import views

urlpatterns = [
    path("", views.index, name="index"),      # /products/
    path("add_products/",views.add_products,name="add_products"),
    path("update_products/<int:id>",views.update_products,name="update_products"),    # /products/<int:product_id>/a
    path("delete_products/<int:id>",views.delete_products,name="delete_products"),  # /products/<int:product_id>/a
]

career/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


# Create your models here.
class Avis(models.Model):
    title = models.CharField(max_length=200)
    tdr = models.FileField(upload_to='tdr/',null=True,blank=True)
    body = CKEditor5Field(config_name='extends')
    status = models.CharField(max_length=100, default="Encour")
    date_line = models.CharField(max_length=100)

class Candidat(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    telephone = models.CharField(max_length=15, blank=True, null=True)
    cv =  models.FileField(upload_to='candidats_docs/')
    lettre_de_motivation =  models.FileField(upload_to='candidats_docs/')
    experience_professionnelle = models.CharField(max_length=100)
    niveau_d_etude = models.CharField(max_length=100)
    specialite = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.prenom} {self.nom}"

career/views.py
from django.shortcuts import render,redirect
from .models import Avis,Candidat
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.contrib import messages

# Create your views here.
def home(request):
    annonce = Avis.objects.all()
    return render(request, 'career/index.html', {'annonce': annonce})

# def avis_recurtement(request):
#     return render(request, 'career/liste_de_avis.html',{'annonce': annonce})

def detail(request,id):
    detail_avis = Avis.objects.get(id=id)
    return render(request,'career/detail.html',{'detail_avis':detail_avis})

@login_required
def postuler(request):
    if request.method == 'POST':
        nom = request.POST.get('nom')
        prenom = request.POST.get('prenom')
        email = request.POST.get('email')
        telephone = request.POST.get('telephone')
        cv = request.FILES.get('cv')
        lettre = request.FILES.get('lettre')
        experience_professionnelle = request.POST.get('experience_professionnelle')
        niveau_d_etude = request.POST.get('niveau_d_etude')
        specialite = request.POST.get('specialite')
        candidat = Candidat(nom=nom,prenom=prenom,email=email,telephone=telephone,cv=cv,lettre_de_motivation=lettre,experience_professionnelle=experience_professionnelle,niveau_d_etude=niveau_d_etude,specialite=specialite)
        candidat.save()
        return redirect('postuler')
    return render(request, 'career/postuler.html')


def login_user(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('career:postuler')
    return render(request, 'career/login.html')

def logout_user(request):
    logout(request)
    return redirect('career:career')
    

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            user = User.objects.create_user(username, email, password)
            user.save()

        except IntegrityError:
            messages.error(request, "Ce nom d'utilisateur est déjà pris. Veuillez en choisir un autre.")
            return render(request, 'career/register.html')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('career:career')
    return render(request, 'career/register.html')

career/templates/career/detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="container my-5">
    <h4>{{detail_avis.title}}</h4>
    <hr>
    <p>{{detail_avis.body|safe}}</p>
    <!-- <img src="{{detail_avis.img.url}}" alt="" class="img-fluid"> -->
    <br><br>
    <div class="row">
        <div class="col-6">
            <a href="{% if request.user.is_authenticated %}{% url 'career:postuler' %}{% else %}{% url 'career:login' %}{% endif %}"
                class="btn btn-primary btn-block">Postuler</a>
        </div>
        <div class="col-6">
            <a href="{{detail_avis.tdr.url}}" class="btn btn-secondary btn-block" download>Telecharger le TDR</a>
        </div>
    </div>
</section>

{% endblock %}

career/templates/career/hero.html
<section id="hero" class="d-flex align-items-center">

    <h5 data-aos="fade-up" data-aos-duration="2000" class="container shadow-2"
        style="background-color: #04041fab; color: #fff;">
        Bienvenue sur le Portail de Recrutement de l'INSEED Tchad !

        Nous sommes ravis de vous accueillir sur notre plateforme dédiée aux opportunités professionnelles et de
        stage.
    </h5>
</section>

career/templates/career/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero Section -->
{% include 'career/hero.html' %}

<section id="AVIS" class="container">
    <div class="my-5">
        <h2>LISTE DES AVIS DE RECRUTEMENT</h2>
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th>INTITULE DE L'AVIS</th>
                    <th>Date limite</th>
                    <th>TDR</th>
                    <th>STATUS</th>
                </tr>
            </thead>
            <tbody>
                {% for i in annonce %}
                <tr>
                    <td>{{i.title}}</td>
                    <td>{{i.date_line}}</td>
                    <td><a href="">{{i.tdr.name|truncatechars:30|upper }}</a></td>
                    {% if i.status == 'Encours' %}
                    <td><a href="{% url 'career:detail' i.id %}">{{i.status }}</a></td>
                    {% else %}
                    <td>Terminer</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
</section>


<section id="STAGE" class="container">
    <h1 class="my-3">Les domaines de stage que nous offrons</h1>
    <div class="row">
        <div class="col-md-4 my-2">
            <div class="card shadow-2">
                <img src="{% static 'career/stat.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="card-text">Statistiques.</h4>
                </div>
                <a class="btn btn-primary" href="">Lire plus</a>
            </div>
        </div>
        <div class="col-md-4 my-2">
            <div class="card shadow-2">
                <img src="{% static 'career/IT.jpeg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="card-text">Informatique.</h4>
                </div>
                <a class="btn btn-primary" href="">Lire plus</a>

            </div>
        </div>
        <div class="col-md-4 my-2">
            <div class="card shadow-2">
                <img src="{% static 'career/CF.webp' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="card-text">Comptabilité.</h4>
                </div>
                <a class="btn btn-primary" href="">Lire plus</a>
            </div>
        </div>
    </div>
</section>

<section id="CONTACT" class="container mt-5">
    <h1 class="mb-4 text-center">CONTACTEZ-NOUS</h1>
    <div class="row">
        <!-- Carte Google Maps -->
        <div class="col-md-6 mb-4 mb-md-0">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3900.8716457636515!2d15.019965075062315!3d12.120933588121686!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x111bd93d226e4d5b%3A0xc57999698c10e87e!2sINSEED!5e0!3m2!1sfr!2std!4v1725136103797!5m2!1sfr!2std"
                width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>

        <!-- Formulaire de Contact -->
        <div class="col-md-6">
            <form>
                <div class="form-group mb-3">
                    <label for="name">Nom</label>
                    <input type="text" class="form-control" id="name" placeholder="Votre nom">
                </div>
                <div class="form-group mb-3">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Votre email">
                </div>
                <div class="form-group mb-3">
                    <label for="message">Message</label>
                    <textarea class="form-control" id="message" rows="4" placeholder="Votre message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

career/templates/career/liste_de_avis.html
<div class="my-5">
    <h2>LISTE DES AVIS DE RECRUTEMENT</h2>
    <table class="table">
        <thead>
            <tr>
                <th>INTITULE DE L'AVIS</th>
                <th>DATE LIMITE</th>
                <th>TDR</th>

            </tr>
        </thead>
        <tbody>
            {% for i in annonce %}
            <tr>
                <td>{{i.title}}</td>
                <td>{{i.date_line}}</td>
                <td><a href="{{ i.tdr.url }}">{{ i.tdr.name}} {{ i.tdr.url }}</a></td>
                <td><a href="{{ i.tdr.url }}">{{ i.tdr.name}} {{ i.tdr.url }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

career/templates/career/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="container my-5">

    <div class="row">

        <div class="col-md-3">
        </div>

        <div class="col-md-6">

            <form action="" method="post">

                {% csrf_token %}

                <div class="form-group">

                    <label for="email">email</label>

                    <input type="text" class="form-control" id="email" name="email">

                </div>

                <div class="form-group">

                    <label for="password">Mot de passe</label>

                    <input type="password" class="form-control" id="password" name="password">

                </div>

                <button type="submit" class="btn btn-primary">Connexion</button>
                <a href="{% url 'career:register' %}" class="btn btn-primary">Inscription</a>

            </form>

        </div>
        <div class="col-md-3">
        </div>
    </div>

</section>

{% endblock %}

career/templates/career/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #242464;">
    <a class="navbar-brand mx-5" href="{% url 'products:index' %}"><img src="{% static 'career/logo.gif' %}" width="90"
            height="70" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
                <a class="nav-link text-white hover-shadow" style="font-size: 20px;"
                    href="{% url 'career:career' %}">ACCUEIL
                    </span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" style="font-size: 20px;" href="{% url 'career:career' %}#AVIS">AVIS DE
                    RECRUTEMENT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" style="font-size: 20px;" href="{% url 'career:career' %}#STAGE">DEMANDE
                    DE STAGE</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link text-white" style="font-size: 20px;" href="{% url 'career:logout' %}">DÉCONNEXION</a>
                {% else %}
                <a class="nav-link text-white" style="font-size: 20px;" href="{% url 'career:login' %}">CONNEXION</a>
                {% endif %}
            </li>


            <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li> -->
        </ul>

    </div>
</nav>

career/templates/career/postuler.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="container">
    <form method="post" action="{% url 'career:postuler' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="nom">Nom :</label>
            <input type="text" class="form-control" id="nom" name="nom">
        </div>
        <div class="form-group">
            <label for="prenom">Prenom :</label>
            <input type="text" class="form-control" id="prenom" name="prenom">
        </div>
        <div class="form-group">
            <label for="email">Email :</label>
            <input type="email" class="form-control" id="email" name="email">
        </div>
        <div class="form-group">
            <label for="telephone">Telephone :</label>
            <input type="text" class="form-control" id="telephone" name="telephone">
        </div>
        <div class="form-group">
            <label for="cv">CV :</label>
            <input type="file" class="form-control" id="cv" name="cv">
        </div>
        <div class="form-group">
            <label for="lettre_de_motivation">Lettre de motivation :</label>
            <input type="file" class="form-control" id="lettre_de_motivation" name="lettre_de_motivation">
        </div>
        <div class="form-group">
            <label for="experience_professionnelle">Experience professionnelle :</label>
            <input type="text" class="form-control" id="experience_professionnelle" name="experience_professionnelle">
        </div>
        <div class="form-group">
            <label for="niveau_d_etude">Niveau d'etude :</label>
            <input type="text" class="form-control" id="niveau_d_etude" name="niveau_d_etude">
        </div>
        <div class="form-group">
            <label for="specialite">Specialite :</label>
            <input type="text" class="form-control" id="specialite" name="specialite">
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
</section>

{% endblock %}

career/templates/career/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="container my-5">
    <h1>Register</h1>
    <hr>
    <form action="{% url 'career:register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% if messages %}
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    {% endif %}
</section>

{% endblock %}