ajax_emp/urls.py
from django.urls import path
app_name = 'ajax_emp'
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('office', views.officeCRUD, name="office"),
    path('employee', views.employeeCRUD, name="employee"),
]

essaie_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('List_product/',include('List_product.urls')),
    path('inseed/',include('inseed.urls')),
    path('forum/', include('forum.urls')),
    path('inseed_apropos/',include('inseed_apropos.urls')),
    path('careers/',include('career.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('intranet/',include('intranet.urls')),
    path('user_manage/',include('user_manage.urls')),
    path('analytique/',include('analytique.urls')),
    path('ajax_emp/',include('ajax_emp.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path

app_name = "forum"

from . import views 

urlpatterns = [
    path('', views.forum_list, name='forum_list'),
    path('discusions_list/<int:forum_id>/', views.discusions_list, name='discusions_list'),
    path('post_list/<int:discusion_id>/', views.post_list, name='post_list'),
    path('add_post/<int:discusion_id>/', views.add_post, name='add_post'),
]

ajax_emp/models.py
from django.db import models
from django.forms import ModelForm
# Create your models here.

class Office(models.Model):
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100)
class Employee(models.Model):
    genders = [
        ('M','Male'),
        ('F','Female'),
    ]
    name = models.CharField(max_length=100)
    email = models.EmailField()
    gender = models.CharField(max_length=100,choices=genders)
    office = models.ForeignKey('Office',on_delete=models.CASCADE)

class OfficeForm(ModelForm):
    class Meta:
        model = Office
        fields = '__all__'

class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

ajax_emp/views.py
from django.shortcuts import render
from .models import OfficeForm,EmployeeForm
from django.http import JsonResponse
# Create your views here.
def home(request):
    officeForm = OfficeForm()
    employeeForm = EmployeeForm()
    context = {
        'officeForm': officeForm,
        'employeeForm': employeeForm
    }
    return render(request,'ajax/index.html',context)

def officeCRUD(request):
    officeForm = OfficeForm()
    if request.method == 'POST':
        officeForm = OfficeForm(request.POST)
        if officeForm.is_valid():
            officeForm.save()
            return JsonResponse({"message": "Office created successfully!"})

def employeeCRUD(request):
    if request.method == 'POST':
        employeeForm = EmployeeForm(request.POST)
        if employeeForm.is_valid():
            employeeForm.save()
    return JsonResponse({"message": "Employee created successfully!"})

ajax_emp/templates/ajax/index.html
{% extends 'index.html' %}

{% block content %}
<section class="container my-5">
    <div>
        <form action="#" id="office">
            {% csrf_token %}

            <h1>Office Form</h1>
            {{officeForm.as_p}}
            <button type="submit">Submit Office</button>
        </form>

        <hr>

        <form action="#" id="employee">
            {% csrf_token %}
            <h1>Employee Form</h1>
            {{employeeForm.as_p}}
            <button type="submit">Submit Employee</button>
        </form>

    </div>
    <div id="result"></div>
</section>
{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
    integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    $(document).ready(function () {
        console.log($(this));
    });
    function officeFormSubmit(e) {
        e.preventDefault()
        body = {}
        $(this).serializeArray().forEach(element => {
            body[element.name] = element.value
        });

        $.ajax({
            url: "{% url 'ajax_emp:office' %}",
            type: 'POST',
            data: body
        })
            .done(function (data) {
                console.log(data);
                e.target.reset()
            })
            .fail(function () {
                alert("Something went wrong");
            })
    }

    function employeeFormSubmit(e) {
        e.preventDefault()
        body = {}
        $(this).serializeArray().forEach(element => {
            body[element.name] = element.value
        });

        $.ajax({
            url: "{% url 'ajax_emp:employee' %}",
            type: 'POST',
            data: body
        })
            .done(data => {
                console.log(data);
                // e.target.reset()
            })
            .fail(() => alert("Something went wrong"))
    }

    $("#office").submit(officeFormSubmit);
    $('#employee').submit(employeeFormSubmit)
</script>
{% endblock scripts %}