ajax_emp/urls.py
from django.urls import path
app_name = 'ajax_emp'
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('office', views.officeCRUD, name="office"),
    path('employee', views.employeeCRUD, name="employee"),
]

career/urls.py
from django.urls import path
from django.conf import settings
from . import views


app_name = "career"

urlpatterns = [
    path('', views.home, name="career"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('postuler/', views.postuler, name="postuler"),
    path('login', views.login_user, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('register', views.register, name="register"),
]

essaie_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('List_product/',include('List_product.urls')),
    path('inseed/',include('inseed.urls')),
    path('forum/', include('forum.urls')),
    path('inseed_apropos/',include('inseed_apropos.urls')),
    path('careers/',include('career.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('intranet/',include('intranet.urls')),
    path('user_manage/',include('user_manage.urls')),
    path('analytique/',include('analytique.urls')),
    path('ajax_emp/',include('ajax_emp.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path

app_name = "forum"

from . import views 

urlpatterns = [
    path('', views.forum_list, name='forum_list'),
    path('discusions_list/<int:forum_id>/', views.discusions_list, name='discusions_list'),
    path('post_list/<int:discusion_id>/', views.post_list, name='post_list'),
    path('add_post/<int:discusion_id>/', views.add_post, name='add_post'),
]

inseed/urls.py
from django.urls import path
app_name = "inseed"

from . import views

urlpatterns = [
    path('',views.inseed,name="inseed"),
]

products/urls.py
from django.urls import path
app_name = "products"
from . import views

urlpatterns = [
    path("", views.index, name="index"),      # /products/
    path("add_products/",views.add_products,name="add_products"),
    path("update_products/<int:id>",views.update_products,name="update_products"),    # /products/<int:product_id>/a
    path("delete_products/<int:id>",views.delete_products,name="delete_products"),  # /products/<int:product_id>/a
]

templates/add_products.html
{% extends 'index.html' %}
{% block content%}

<p style="background-color: rgba(78, 192, 63, 0.582);">
    {% if messages %} {% for message in messages %} {{ message }} {% endfor %} {% endif %}
</p>
{% load static %}
<form method="POST" action="{% url 'products:add_products' %}">
    {% csrf_token %}
    <div>{{form.as_p}}</div>
    <input type="submit" value="submit" />
</form>
{% endblock%}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <!-- <link rel="stylesheet" href="/products/static/style.css"> -->
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'inseed/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
      rel="stylesheet"
      type="text/css"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js"
      integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
      type="text/javascript"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <!-- <style>
    #google_translate_element {
        padding: 10px 20px;
        position: absolute;
    }
</style> -->

  <body>
    <div id="google_translate_element"></div>
    <header class="header">
      <div class="content">
        <div class="logo">
          <img src="{% static 'img/logo.jpg' %}" alt="" />
        </div>
        <nav class="navbar">
          <ul class="links">
            <li class="link">
              <a href="{% url 'products:index' %}">Accueil</a>
            </li>
            <li class="link">
              <a href="{% url 'analytique:home' %}">analytique</a>
            </li>
            <li class="link">
              <a href="{% url 'ajax_emp:home' %}">Ajax</a>
            </li>

            <li class="link">
              <a href="{% url 'List_product:list_products' %}"
                >Liste products</a
              >
            </li>
            <li class="link">
              <a href="{% url 'products:add_products' %}">Add product</a>
            </li>
            <li class="link"><a href="{% url 'inseed:inseed' %}">inseed</a></li>
            <li class="link">
              <a href="{% url 'forum:forum_list' %}">forum_list</a>
            </li>
            <li><a href="{% url 'career:career' %}">Career</a></li>

            <li class="link" style="position: relative">
              <a href="">apropos</a>
              <ul
                style="
                  position: absolute;
                  right: 0;
                  top: 50px;
                  background-color: blue;
                  width: 300px;
                "
              >
                <li>
                  <a href="{% url 'inseed_apropos:apropos' %}"
                    >Connaitre l'inseed</a
                  >
                </li>
                <li>
                  <a href="{% url 'inseed_apropos:organigrame' %}"
                    >Organisation et Fonctionnement</a
                  >
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </header>

    {% block content%} {% endblock %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement(
          {
            pageLanguage: "en", // Change 'en' pour la langue par défaut de ton site
            includedLanguages: "en,fr,es,de,it,ar", // Liste des langues que tu veux proposer
            layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
          },
          "google_translate_element"
        );
      }
    </script>
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

templates/update_products.html
{% extends 'index.html' %}
{% block content%}

{% load static %}
<form method="POST" action="">
    {% csrf_token %}
    <div>{{form.as_p}}</div>
    <input type="submit" value="submit" />
</form>
{% endblock%}